[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --cache /tmp/npm-cache"]

[phases.build]
cmds = ["rm -rf node_modules/.cache", "npm run build:all"]

[start]
cmd = "node dist/apps/api-gateway/main.js"
